# Generated by Django 3.2.25 on 2024-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_destinationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
