# Generated by Django 3.2.25 on 2024-09-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_message_review_room_starrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message')),
            ],
        ),
    ]
